<?php ?>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="danceStyle.css">
        <title>Dance</title>        
    </head>
    <body>
        <div id="coverPic"> </div>         
        <div id="titlePic"> </div>        
        <div id="navBar">
            <div class="navBackground"></div>
            <div class="navImgs">
                <img id="navImg"  src="img/tennis-png-free-download-5.png" alt=""/>
                <img id="navImg" src="img/tennis-png-free-download-5.png" alt=""/>
                <img id="navImg" src="img/tennis-png-free-download-5.png" alt=""/>
                <img id="navImg" src="img/tennis-png-free-download-5.png" alt=""/>
                <img id="navImg" src="img/tennis-png-free-download-5.png" alt=""/>
                <img id="navImg" src="img/tennis-png-free-download-5.png" alt=""/>
            </div>
            <div class="navText">                
                <a href="" id="navText" class="navFood">Food</a>
                <a href="" id="navText"class="navHistory">History</a>
                <a href="" id="navText" class="navJazz">Jazz</a>
                <a href="" id="navText"class="navDance">Dance</a>
                <a href="" id="navText" class="navContact">Contact us</a>
                <a href="" id="navText" class="navCart">Cart</a>
            </div>
            <div class="navlogoT">
                <img id="navImg"  src="img/tennis-png-free-download-5.png" alt=""/><br/>                
            </div>
            <div class="navText">
                <a href="" id="navText" class="navHF">Haarlem Festival</a>
            </div>            
        </div>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vehicula ligula non neque tempus, sit amet dapibus ex auctor. Nullam vitae nunc dapibus, auctor nulla quis, finibus mi. Aliquam non libero et ante mattis scelerisque id in nulla. Quisque turpis ex, viverra id sem at, placerat pretium nibh. In vel mattis nisl. Phasellus at sodales nulla. Maecenas venenatis dolor at augue molestie venenatis. Duis pulvinar vel odio sed tristique. Morbi imperdiet malesuada aliquet.

Sed vel magna id nibh sodales ultricies bibendum ut risus. Nulla posuere arcu et justo maximus finibus. Nulla quis nisl ante. Proin lacus mi, feugiat id turpis et, facilisis convallis velit. Vivamus vulputate ut augue vel ullamcorper. Phasellus sollicitudin, velit non mollis venenatis, ex diam tempor eros, ut pharetra massa ligula at ipsum. Sed eget metus a metus volutpat fringilla. In hac habitasse platea dictumst. In a eleifend diam. Fusce sagittis dictum eros, non mattis nisl placerat nec. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin et convallis diam. Nullam ut metus at quam molestie luctus quis blandit lectus. Pellentesque quis feugiat neque, finibus porttitor lectus. Vestibulum eget ipsum sit amet dolor molestie sodales sed non purus.

Vivamus libero sapien, rutrum in dignissim at, blandit ut lacus. Sed lobortis, enim quis condimentum posuere, dui nunc faucibus nibh, et ultrices ipsum nisi et libero. Curabitur leo est, porta vitae sodales eu, cursus et sapien. Suspendisse finibus erat ac nisl gravida, placerat ultrices ligula sagittis. Vestibulum laoreet rhoncus aliquam. Sed interdum lorem vel odio vulputate, eu convallis neque ornare. Etiam a finibus augue. Nunc malesuada dolor quam, vitae luctus enim finibus eu. Nulla facilisi. In dictum imperdiet erat, a vehicula urna tempor ac. Integer tellus tellus, egestas facilisis sagittis quis, finibus lobortis lorem. Sed facilisis mi id faucibus varius. Morbi sit amet auctor lorem. Nam ac purus fermentum lorem euismod vulputate ut non neque. Maecenas lorem sapien, bibendum vel tempor sit amet, ornare eget arcu. Nunc mollis sed erat sed tristique.

Sed elementum libero at leo imperdiet lobortis. Vestibulum aliquet scelerisque eros eget posuere. Mauris enim sapien, posuere vel bibendum in, vulputate id est. Sed vel tellus iaculis, finibus urna sit amet, tempor dolor. Sed consequat risus ipsum. Donec scelerisque, lectus ut sodales semper, massa risus fringilla purus, sed luctus ligula mi at lectus. Sed eleifend urna a eros rutrum dictum. Fusce laoreet volutpat quam sit amet rhoncus. Vivamus pulvinar luctus neque, vitae auctor est pellentesque ac. Cras tincidunt ligula felis, sit amet ullamcorper mauris porttitor eu. Vivamus non eleifend tellus. Donec cursus id odio fermentum commodo. Aliquam ante urna, scelerisque ut dignissim non, mattis id odio. Cras tellus lectus, euismod vel justo et, vulputate sollicitudin nunc. Nam efficitur egestas massa ut imperdiet. Ut congue mi eu ligula fermentum, posuere rutrum lorem elementum.
        </p>
        <script>
            window.onscroll = function () {
                myFunction()
            };

            var navbar = document.getElementById("navBar");
            var sticky = navbar.offsetTop;

            function myFunction() {
                if (window.pageYOffset >= sticky) {                    
                    document.getElementById("navBar").style.top=-300;
                    navbar.classList.add("newNav");
                } else {
                    navbar.classList.remove("newNav");
                }
            }
        </script>
    </body>
</html>

